<?php

namespace Richpolis\UsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function queryFindUsuarios($buscar = "")
    {
        $em = $this->getEntityManager();
        if(strlen($buscar)==0){
            $consulta = $em->createQuery('SELECT u '
                . 'FROM UsuariosBundle:Usuario u '
                . 'ORDER BY u.nombre ASC, u.apellido ASC');
        }else{
            $consulta = $em->createQuery("SELECT u "
                . "FROM UsuariosBundle:Usuario u "
                . "WHERE u.nombre LIKE :nombre OR u.apellido LIKE :apellido OR u.email LIKE :email "
                . "ORDER BY u.nombre ASC, u.apellido ASC");
            $consulta->setParameters(array(
                'nombre' => "%".$buscar."%",
                'apellido' => "%".$buscar."%",
                'email' => "%".$buscar."%"
            ));
        }
        return $consulta;
    }
    
    public function findUsuarios($buscar = ""){
        return $this->queryFindUsuarios($buscar)->getResult();
    }
}
