backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /

dreams:
    resource: "@DreamsBundle/Controller/"
    type:     annotation
    prefix:   /

usuarios:
    resource: "@UsuariosBundle/Controller/"
    type:     annotation
    prefix:   /

galerias:
    resource: "@GaleriasBundle/Controller/"
    type:     annotation
    prefix:   /

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect
 
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login
 
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

twitter_login:
    pattern: /login/check-twitter

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"