security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Richpolis\UsuariosBundle\Entity\Usuario:
          algorithm: sha512
          encode-as-base64: true
          iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USUARIO
        ROLE_SUPER_ADMIN: [ROLE_USUARIO, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: Richpolis\UsuariosBundle\Entity\Usuario, property: email }

    firewalls:
      dev:
        pattern:  ^/(_(profiler|wdt)|css|images|js)/
        security: false
      admin:
        pattern: ^/admin
        provider: user_db
        form_login:
            login_path: admin_login
            check_path: admin_login_check
            remember_me: true
            use_referer: false
        logout:
            path: admin_logout
            target: admin_login
        security: true
        anonymous: true
      frontend:
        pattern:  ^/
        provider: user_db
        form_login:
            login_path: login
            check_path: login_check
            remember_me: true
            use_referer: false
        oauth:
            resource_owners:
                facebook:    "/login/check-facebook"
                twitter:     "/login/check-twitter"
            login_path:     /login
            failure_path:   /login 
            oauth_user_provider:
               #servicio para logear al usuario.
                service: my_user_provider
        logout:
            path: logout
            target: login
        remember_me:
            key: "%secret%"
            lifetime: 31536000
            path: /.*
            domain: ~
            always_remember_me: true
        security: true
        anonymous: true

    access_control:
        - { path: ^/s, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USUARIO] }