<?php

namespace Richpolis\DreamsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponenteRepository extends EntityRepository
{
    public function getMaxPosicion($dream){
        $em=$this->getEntityManager();
       
        $query=$em->createQuery('
            SELECT MAX(c.position) as value 
            FROM DreamsBundle:Componente c 
            WHERE c.dream =:dream
            ORDER BY c.position ASC
        ')->setParameter('dream', $dream);
        
        $max=$query->getResult();
        return $max[0]['value'];
    }
}
