<?php

namespace Richpolis\DreamsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Richpolis\UsuariosBundle\Entity\Usuario;

/**
 * DreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DreamRepository extends EntityRepository
{
    
    
    public function queryFindDreams($buscar = "",$usuario=null)
    {
        $em = $this->getEntityManager();
        if(strlen($buscar)==0){
            if($usuario == null){
                $consulta = $em->createQuery('SELECT h '
                    . 'FROM DreamsBundle:Dream h '
                    . 'ORDER BY h.fecha ASC');
            }else{
                $consulta = $em->createQuery("SELECT h "
                    . "FROM DreamsBundle:Dream h "
                    . "WHERE h.usuario=:usuario  "    
                    . "ORDER BY h.dream ASC");
                $consulta->setParameters(array(
                    'usuario' => $usuario->getId(),
                ));
            }
        }else{
            if($usuario == null){
                $consulta = $em->createQuery("SELECT h "
                    . "FROM DreamsBundle:Dream h "
                    . "WHERE h.dream LIKE :dream  "    
                    . "ORDER BY h.dream ASC");
                $consulta->setParameters(array(
                    'dream' => "%".$buscar."%",
                ));
            }else{
                $consulta = $em->createQuery("SELECT h "
                    . "FROM DreamsBundle:Dream h "   
                    . "WHERE h.dream LIKE :dream  "
                    . "AND h.usuario=:usuario  "    
                    . "ORDER BY h.dream ASC");
                $consulta->setParameters(array(
                    'dream' => "%".$buscar."%",
                    'usuario' => $usuario->getId(),
                ));
            }
        }
        return $consulta;
    }
    
    public function findDreams($buscar = "",$usuario=null){
        return $this->queryFindDreams($buscar,$usuario)->getResult();
    }
    
    public function getCountDreamsEnYears($year, Usuario $usuario)
    {
        $em = $this->getEntityManager();
        $emConfig = $em->getConfiguration();
        $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
        $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
        $emConfig->addCustomDatetimeFunction('DAY', 'DoctrineExtensions\Query\Mysql\Day');
            $consulta = $em->createQuery(
                "SELECT a.imagen as imagen, MONTH(h.fecha) as mes "
                . "FROM DreamsBundle:Dream h "
                . "JOIN h.usuario u "
                . "JOIN h.hijo a "    
                . "WHERE YEAR(h.fecha) =:year "
                . "AND u.id=:usuario "    
                . "ORDER BY mes ASC");
            $consulta->setParameters(array(
                'year'      =>  $year,
                'usuario'   =>  $usuario->getId(),
            ));
        return $consulta->getResult();
    }
    
    public function getDreamsDelMes($year,$mes, Usuario $usuario)
    {
        $em = $this->getEntityManager();
        $emConfig = $em->getConfiguration();
        $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
        $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
        $emConfig->addCustomDatetimeFunction('DAY', 'DoctrineExtensions\Query\Mysql\Day');
            $consulta = $em->createQuery(
                "SELECT h, c, u, uh "
                . "FROM DreamsBundle:Dream h "
                . "JOIN h.componentes c "
                . "JOIN h.usuario u "
                . "JOIN u.hijos uh "
                . "WHERE YEAR(h.fecha) =:year "
                . "AND MONTH(h.fecha)=:mes "
                . "AND u.id=:usuario "    
                . "ORDER BY h.fecha ASC");
            $consulta->setParameters(array(
                'year'  =>  $year,
                'mes'   =>  $mes,
                'usuario'   =>  $usuario->getId(),
            ));
        return $consulta->getResult();
    }
}
