<?php

namespace Richpolis\DreamsBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Richpolis\UsuariosBundle\Entity\Usuario;

/**
 * DreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DreamRepository extends EntityRepository
{
    
    
    public function queryFindDreams($buscar = "",$usuario=null,$operador="=")
    {
        $em = $this->getEntityManager();
        if(strlen($buscar)==0){
            if($usuario == null){
                $consulta = $em->createQuery('SELECT h '
                    . 'FROM DreamsBundle:Dream h '
                    . 'ORDER BY h.titulo ASC');
            }else{
                $consulta = $em->createQuery("SELECT h "
                    . "FROM DreamsBundle:Dream h "
                    . "WHERE h.usuario$operador:usuario "    
                    . "ORDER BY h.titulo ASC");
                $consulta->setParameters(array(
                    'usuario' => $usuario->getId()
                ));
            }
        }else{
            if($usuario == null){
                $consulta = $em->createQuery("SELECT h "
                    . "FROM DreamsBundle:Dream h "
                    . "WHERE h.titulo LIKE :titulo OR h.lugar LIKE :lugar OR h.dream LIKE :dream "    
                    . "ORDER BY h.titulo ASC");
                $consulta->setParameters(array(
					'titulo' => "%".$buscar."%",
                	'lugar' => "%".$buscar."%",
                	'dream' => "%".$buscar."%"
                ));
            }else{
                $consulta = $em->createQuery("SELECT h "
                    . "FROM DreamsBundle:Dream h "   
                    . "WHERE h.titulo LIKE :dream  "
                    . "AND h.usuario$operador:usuario AND (h.titulo LIKE :titulo OR h.lugar LIKE :lugar OR h.dream LIKE :dream) "    
                    . "ORDER BY h.titulo ASC");
                $consulta->setParameters(array(
                    'usuario' => $usuario->getId(),
                    'titulo' => "%".$buscar."%",
                    'lugar' => "%".$buscar."%",
                    'dream' => "%".$buscar."%"
                ));
            }
        }
        return $consulta;
    }
    
    public function findDreams($buscar = "", $usuario=null, $operador="="){
        return $this->queryFindDreams($buscar,$usuario,$operador)->getResult();
    }
    
    public function queryFindNewDreams() 
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT h '
                . 'FROM DreamsBundle:Dream h '
                . 'WHERE h.compartir=:isCompartir '
                . 'ORDER BY h.createdAt ASC');
        $consulta->setParameters(array(
            'isCompartir' => true,
        ));
        return $consulta;
    }

    public function findNewDreams($maxresults = 5){
        return $this->queryFindNewDreams()->setMaxResults($maxresults)->getResult();
    }
    
    public function queryFindForMoreComments() 
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('SELECT h, SIZE(h.mensajes) AS HIDDEN contMensajes '
                . 'FROM DreamsBundle:Dream h '
                . 'JOIN h.mensajes m '
                . 'WHERE h.compartir=:isCompartir '
                . 'ORDER BY contMensajes DESC');
        $consulta->setParameters(array(
            'isCompartir' => true,
        ));
        return $consulta;
    }

    public function findForMoreComments($maxresults = 5){
        return $this->queryFindForMoreComments()->setMaxResults($maxresults)->getResult();
    }
}
